### ISSUE TITLE
MyCommunity Link Missing

### ISSUE THREAD

**Issue by knovotney** [MyCaert/Issues-Enhancements#254] opened 2017-08-18 14:04 UTC
![image](https://user-images.githubusercontent.com/21039374/29462176-743d1c28-83fc-11e7-990f-de6142ab6bf4.png)
ASPR:C7-3: Exploring the Dairy Industry does not have a "Click to See More" link in Animal, Plant & Soil Science.

Please let us know when it is fixed.

**Comment by mnichols13** [comment] 2017-08-18 14:23
When I mark the last posted material - pending approval and take it away, this corrects the issue.  
The post creating the issue is from 6/6/17 - Wendy Leneerts 
Please take a look at this material: Dairy Eunit WS

**Comment by knovotney** [comment] 2017-08-18 14:34
@mnichols13 @bguerrettaz How will we as admin know something is needing approval?

**Comment by mnichols13** [comment] 2017-08-18 14:37
I marked it pending approval..

**Comment by knovotney** [comment] 2017-08-18 16:22
@mnichols13 @bguerrettaz How will we as admin know something is needing approval?

**Comment by bguerrettaz** [comment] 2017-09-08 17:35
Sorry, I'm coming back to this issue.  What exactly is the question?

**Comment by knovotney** [comment] 2017-09-08 19:36
Blake,

If someone adds something to My Community, does it always need our approval? If not, how will we know when something needs approval?

**Comment by bguerrettaz** [comment] 2017-09-12 01:48
I'm not sure exactly how MyCommunity was designed, I wasn't the developer
on that effort.  I do see an 'approved' or 'rejected' selection on the
admin side for MyCommunity, under search, so I'm assuming someone needs to
approve it.

Dan, Mindy - have you had to approve in the past?

Brian - how was this designed?  Who is contacted when someone posts
something?

Thanks,
Blake

**Comment by dpentony** [comment] 2017-09-12 12:42
Usually, we do not have to approve a post. However, from the admin, we can reject an item once it has been posted. This one was unusual in that it would not show up until we approved it.

This is not enough of an issue to leave open. I am closing it.

**Closed by dpentony** 2017-09-12 12:42 UTC

**Comment by bguerrettaz** [comment] 2017-09-12 14:14
Yes, i think you may need to approve
