### ISSUE TITLE
High Priority - Multiple Instance of Quizzes Being Saved After Parameters are Changed

### ISSUE THREAD

**Issue by dpentony** [MyCaert/Issues-Enhancements#179] opened 2015-11-10 15:41 UTC
Matthew Lee is a teacher in WI. He has a course called Exploring Plants, Animals, and Food. Whenever he changes the parameters for a test in this course and saves the changes, THREE new instances of the quiz are saved. It is listing the course name (Exploring Plants, Animals, and Food) over three lines Exploring Plants: Animals: and Food, and associating one test with each line. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/11066392/9d1f7bbc-878d-11e5-8a56-6196107b2278.png)

When you look at the parameters page for the three highlighted instances, none of them have the course name highlighted in the pull down menu. See below.

![image](https://cloud.githubusercontent.com/assets/5790325/11066493/167ba454-878e-11e5-9294-7a68e342250f.png)

It almost appears that as he changes the parameters on a test, three new instances of the test are created but they do not replace the original version. Instead of replacing the original version that was created, it is adding three more instances.

He almost mentioned that he did not think the parameter changes he was making are being saved. However, when I look at the different instances of the tests, I see differences in how the parameters are set.

**Comment by bguerrettaz** [comment] 2015-11-13 12:42
This was caused by the comma's in the title of the courses, it was splitting by a space and comma.  I have corrected this by accounting for comma's in certain course names.

Please test and confirm.

**Comment by dpentony** [comment] 2015-11-13 13:45
I don't see any difference. The quizzes for the Exploring Plants, Animals, and Foods course are still displayed in three lines on the edit quiz page:

![image](https://cloud.githubusercontent.com/assets/5790325/11147211/fa063eda-89d9-11e5-9b69-971db71a4a95.png)

Also, when you go to the quiz parameters page for any of these quizzes, the course name is not highlighted in the pull down:

![image](https://cloud.githubusercontent.com/assets/5790325/11147287/7f748ffe-89da-11e5-8120-431395bfbbe0.png)

**Comment by bguerrettaz** [comment] 2015-11-13 14:01
That's because those quizzes were inserted into the database before the fix j out into place.  Those should be deleted/removed as they don't relate to any course.  The comma was problem and that has been fixed.

You don't see those highlighted because the three quizzes don't relate to any quiz listed.

A good test would be to recopy a set and quizzes and make sure to select the course with commas...you'll then see that the problem no longer exists.

Blake

**Comment by dpentony** [comment] 2015-11-13 14:13
I will let the teacher know we believe it has been fixed. I will let him delete the quizzes. I don't feel comfortable doing so. I'll re-open this issue if he finds something different.

**Comment by bguerrettaz** [comment] 2015-11-13 14:40
Sounds good, thanks.

**Comment by dpentony** [comment] 2015-11-13 15:59
Here is a another case of multiple copies of the quiz being saved when a teacher changes a parameter. In this case, it is Jay Williams ag account in IL. It is for his BSAA Plant Science 15_16_1A course. He made changes to the quizzes for this course and multiple copies were saved. Only one of each instance of the quizzes is associated to the correct course when you look at the parameters. Could this be due to the fact he has a bunch of underscores in the coure name? if so, we need to somehow address how we handle such characters. A lot of teachers have special characters in their course names. He said he had no problems before today. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/11150353/40e225ea-89ed-11e5-897c-e75348208ce4.png)

**Comment by dpentony** [comment] 2015-11-13 20:35
We just had another case of where multiple copies of the quiz are being saved when a teacher changes a quiz's parameters. It is Doug Falk's IL ag account. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/11156768/772aa6b0-8a13-11e5-9c6b-afd1e8c8612a.png)

I am guessing it is because he has a hyphen in the course name. Again, we need to make allowance for these special characters in the course names.

**Comment by bguerrettaz** [comment] 2015-11-13 22:02
I'm having a hard time recreating this, even with Doug Falk's account.  I used the same quizzes as you have highlighted about and changed the dates of the quizzes, and it didn't create multiples.

Can you please try to recreate and walk me through the steps?  If I can get it to happen for me, I'll be able to troubleshoot.

Thanks,
Blake

**Comment by dpentony** [comment] 2015-11-13 22:16
I was able to replicate when I chose a quiz that there was only one copy of. I chose Agronomy Math. The original one had a a deactivate date of 12/10/2013. I edited that quiz and changed the deactivate date to 12/10/2015. After doing that, two instances of the quiz show up. It seems to be saving the newly edited copy in ADDITION to keeping the original copy instead of REPLACING the original.

![image](https://cloud.githubusercontent.com/assets/5790325/11159037/ddbb4822-8a21-11e5-9320-f613c5ded968.png)


Also, when you look at the parameters for the second instance, there is no course selected in the pulldown list even though the Edit Quiz page says it is assigned to the Advanced Ag Science - Crops course.

**Comment by bguerrettaz** [comment] 2015-11-13 22:43
I found the issue, it had to do with trimming a string for comparison.  The string wasn't being trimmed and there was a space at the end, making them in-equal.

I have fixed this and tested, looks good.

Please test and confirm.

**Comment by dpentony** [comment] 2015-11-14 16:16
I'm hesitant to do a lot of testing under their accounts, so I've alerted each teacher. I've told them it is fixed and asked them to confirm.

One question: was this affecting only course outlines with special characters like underscore s, hyphen s, and commas?

**Comment by bguerrettaz** [comment] 2015-11-14 16:28
Possibly, the space at the end of the name of the quiz class could've been
caused by special characters or could've been there in other scenarios as
well.

I've accounted for spaces before and after the name now.

Blake

**Comment by dpentony** [comment] 2015-11-16 19:30
We are still monitoring this. A couple of teachers reported today that they had mutiple copies of a quiz after making parameter changes. We are trying to determine if this is a result of the changes they made today or did the multiple copies get created last week before you made the latest changes. We've been unable to duplicate the issue as of now.

**Comment by bguerrettaz** [comment] 2015-11-16 19:30
Sounds good, thanks.

**Comment by dpentony** [comment] 2015-11-16 20:02
I think we might have determined part of why there might be multiple copies of a quiz being created. I had a quiz called Dan 11.15.15 test. I created and did not assign it to a quiz class. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/11192832/de94f57e-8c68-11e5-983e-c8ff00b71c9e.png)

I then changed the course parameter and assigned it to my Ag Power 1 course. See below:

![image](https://cloud.githubusercontent.com/assets/5790325/11192860/0553019c-8c69-11e5-9774-5f8c0877295b.png)

However, when you click Save Quiz Changes and the parameters page refreshes it still shows the quiz as being assigned to no quiz class. See below. Shouldn't it show the updated parameters page where it is assigned to Ag Power 1? Teachers could view this as the first parameter change they made did not stick and they will try it again,

![image](https://cloud.githubusercontent.com/assets/5790325/11192944/68f89bda-8c69-11e5-8fde-098b9f10cb6c.png)

The fact that the quiz parameter page did not update to the second course the test was assigned to (Ag Power 1) leads to confusion if the teacher next goes to change another parameter. The teacher thinks they are changing the parameter for that quiz assigned to Ag Power 1, but since the parameter page did not update after changing the course to Ag Power 1, and they change another parameter (like deactivate date), it is changing that parameter for the quiz assigned to No Quiz Class while the teacher thinks they're changing it for the quiz assigned to Ag Power 1.

**Comment by bguerrettaz** [comment] 2015-11-17 01:41
I was also able to recreate the issue.  I put in a fix for what I found and
tested.  I validated that it no longer inserted another quiz and that it
updated the correct parameters on the correct quiz.

Please test and confirm.

Blake

**Comment by dpentony** [comment] 2015-11-17 02:27
I agree the changes you made work. I am just not sure about one aspect of the changes. I created a test called DP 11.15.15 and did not assign it to a course. I then edited the parameter so that it is assigned to the VA course. The change stuck when the parameters page refreshed - the course it is assigned to was the VA course.

When I went to the edit quizzes page, it only showed the one instance of that quiz being assigned to the VA course. So, the first instance of the quiz that was assigned to NO Quiz Class was REPLACED by the one assigned to the VA course. Do we want it to replace the previous copy of the quiz or add a second copy of the quiz under the new course where it is assigned? The whole purpose of this change originally was to be able to assign a quiz to more than one course. Although it now does that if you use the shift/control keys to select more than one course, it might be confusing.

@mnichols - I will call you around 8 tomorrow to discuss this.

**Comment by bguerrettaz** [comment] 2015-11-18 01:39
Ok, I 'think' I understand what you're wanting.  I put code in place to account for that (pretty much make it what it was before last night's change).

Here is the breakdown:
- If the course has changed in the parameters page, then a copy of the quiz and the currently selected parameters will be inserted/created for each new course selected
- If the parameters change for one course and the course didn't change, the quiz will simply be updated.

Please test and confirm these scenarios and any others you can think of.  

If there are still issues, please send me a complete list of steps to recreate the issue.

Thanks,
Blake

**Comment by dpentony** [comment] 2015-11-18 02:03
This all sounds good. I am in a hotel with crummy wireless due to storms. I cannot test it out.

Mindy, could you please test and let us know if all looks good?

**Comment by mnichols13** [comment] 2015-11-18 13:02
it looks like we are back to where we were on Monday, which is better, but not the way we want it.  Blake, I think this would be better explained over the phone, can you just call me when you are available? x 133

**Comment by bguerrettaz** [comment] 2015-11-19 02:07
I will try to call tomorrow when I have a free moment.

I thought after Dan's last email, we wanted to go back to where we were:

"After further testing this morning, I think we want a copy of the test
created WHEN THE COURSE THE TEST HAS BEEN ASSIGNED TO HAS CHANGED. That is
the way it was before the change last night."

**Comment by dpentony** [comment] 2015-11-19 03:12
Please wait until you speak with Mindy to proceed, but I believe  the issue is this: when the quiz is assigned to no quiz class and you change the parameter so that it is assigned to a different course and click save quiz changes, the parameter page does not show the new course the quiz is assigned to. When the parameter page refreshes, it still shows that it is still assigned to no quiz class. 

Mindy can walk you through it when you call her tomorrow.

**Comment by mnichols13** [comment] 2015-11-19 20:25
Blake,  Dan and I talked about this issue.   I think for now we would like to leave it as is.  However,  could you please provide us with an estimate for a pop up message once a teacher assigns a quiz to a new course.  This may help with the confusion since it does revert back to the original quiz.  The pop up message might say something like, "Your quiz was successfully assigned to a new course, please return to the Edit Quiz page for...... additional changes, or to see your multiple copies...

**Comment by bguerrettaz** [comment] 2015-11-19 20:28
Sure, should only take a hour or two.

**Comment by mnichols13** [comment] 2015-11-19 20:32
Ok, I think Dan is going to email you later.  We will just need to tweak the wording so that it makes sense and it concise for the reader.

**Comment by dpentony** [comment] 2015-11-20 01:23
I am going to talk with Mindy more next week when I am back in the office so we can get the wording right.
@bguerrettaz - I'd like to talk about doing more of this sort of thing when we make changes. We need to do a better job communicating upgrades/changes to our customers.

**Comment by bguerrettaz** [comment] 2015-11-20 01:38
I agree, I told Mindy my idea for communicating changes/upgrades.  I can
elaborate further after you guys talk next week and send me your ideas.

Thanks,
Blake

**Comment by dpentony** [comment] 2015-11-23 16:18
@bguerrettaz  - We were thinking wording like the followingto appear as a pop-up on the parameters page after they have assigned a quiz to a different course:

"Your quiz has been assigned to the new course. Please return to the Edit Quiz page to make additional edits or to see other instances of this quiz".

Also, on the parameters page next to the course is an "i". If you mouse over it a pop-up window appears with text. We're wondering if the text in that window could be revised to say:

"You can now assign a quiz to more than one course. Just use the pulldown menu of courses to do so.”

I see this revised window as a pop-up that comes up automatically (without mousing over the i). It would automatically come up for the next 3 to 6 months in order to highlight the fact that a quiz can now be assigned to more than one course.

Let us know your thoughts.

**Comment by bguerrettaz** [comment] 2015-11-30 02:23
Yes, this is no problem.

All of this should take 2-3 hours or so.

Do you want it to be 3 months or 6 months?

Thanks,
Blake

**Comment by dpentony** [comment] 2015-11-30 02:46
6 months

**Comment by bguerrettaz** [comment] 2015-12-09 03:17
Ok, I have everything done except for auto-showing the information bubble on page load.  Because of the way it was originally written, it is taking a bit longer.  I should have is done by tomorrow evening.

Please test and confirm the message popup is showing when desired and the new information bubble has the correct verbiage.

Thanks,
Blake

**Comment by dpentony** [comment] 2015-12-09 13:51
I'm not seeing this pop-up on the parameters page after I have assigned the quiz to a different course:

Your quiz has been assigned to the new course. Please return to the Edit Quiz page to make additional edits or to see other instances of this quiz".

**Comment by bguerrettaz** [comment] 2015-12-09 14:03
Here is a screenshot after assigning to more than one class:

![image](https://cloud.githubusercontent.com/assets/5695475/11687250/33a3d08c-9e4b-11e5-8e96-648282ddfde6.png)

One thing that might have been missed is I created that popup if you select more than one quiz (copying to one or more quizzes).  I think the gap might be if the user simply selects another quiz class to do a copy that way?

**Comment by dpentony** [comment] 2015-12-09 14:12
I see that now. I think the pop-up needs to appear even is the user simply selects another quiz class.

**Comment by bguerrettaz** [comment] 2015-12-09 14:12
Sounds good, I'll make that change.

**Comment by bguerrettaz** [comment] 2015-12-10 03:16
This is fixed.  Please test and confirm.

**Closed** 2015-12-10 13:34 UTC
