### ISSUE TITLE
Implementation of Authentication Upgrades

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#200] opened 2016-07-11 19:41 UTC
Our IL CTE teachers cannot open any lesson plans or E-units.  Assuming this has to do with the authentication changes you are working on.   Here is the error message:
CDID: 88
Microsoft VBScript runtime error '800a000d'

Type mismatch: 'RS'

/authenticationCheck.asp, line 58
'
Please advise on how quickly we can get things back to normal.

**Comment by bguerrettaz** [comment] 2016-07-11 20:00
I'll deactivate the auth engine until I can look into the root cause
tonight.

Blake

**Comment by dpentony** [comment] 2016-07-11 20:03
It only seems to be affecting the CTE users. The ag users are fine.

**Comment by bguerrettaz** [comment] 2016-07-11 20:06
I've deactivated, I'll take a look at why the CTE teachers had an issue
this evening.  I have an idea.

Blake

**Comment by bguerrettaz** [comment] 2016-07-12 02:07
i have fixed the issue with the CTE teachers.

I have also installed the PPT changes.

Eunits, PPTs and Lesson Plans are all installed.

Please test and let me know of any issues.

Thanks,
Blake

**Comment by bguerrettaz** [comment] 2016-07-12 15:32
Any issues so far?  Any questions come up during your testing?

**Comment by dpentony** [comment] 2016-07-12 15:46
I've not encountered any issues so far during my testing. We'll continue testing this afternoon.

**Comment by dpentony** [comment] 2016-07-12 20:13
We are testing the auth changes and have a couple of questions.

When I am in Chrome and click on a lesson or Eunit, the file itself downloads automatically. So there is no link for me to test against the auth changes. When in Firefox, the file does not actually download and there is a link in the browser window that I can cut and paste to test the changes. They work fine in Firefox but I cannot test them in Chrome since the file itself downloads.

Mindy is having a similar experience, but in her case, the file downloads automatically in Firefox, so she cannot test it.

We both have this same issue when opening PPTs regardless of browsers. In all instances, the file itself downloads and there is no link we can past into to test.

Do these differences have to do with browser settings? If so how do we control that across users?

**Comment by bguerrettaz** [comment] 2016-07-12 20:16
I have it set in the code to show PDF's in the browser, IF the browser has
a PDF reader.  Chrome should have that defaulted.  For example, when I test
PDF's (eUnits and Lesson Plans) in Chrome, they are shown in the browser,
they don't automatically download.

All PPT's will download automatically as there generally isn't a reader
embedded within the browsers, so that is natural.

One way to test these and get the links and to right click the links and
select 'Copy Link Address'.

Let me know if that helps.

Thanks,
Blake

**Comment by dpentony** [comment] 2016-07-12 20:45
If you have it set in the code to show the PDFs in the browser, why do they download for me in Chrome but not for Mindy? Why is the situation reversed for us in Firefox?

**Comment by bguerrettaz** [comment] 2016-07-12 20:57
Here is a link that could help.  Please try this and let me know if that
resolves:

https://support.google.com/chrome/answer/6213030?hl=en

Thanks,
Blake

**Comment by dpentony** [comment] 2016-07-13 13:35
I was able to do this and now see the PDFs as a link instead of the file downloading.

**Comment by dpentony** [comment] 2016-07-14 13:38
I've noticed an issue when we are logged in on the admin page. If I try to access the Missing file report and click to open a file, it redirects me back to the user page and says I have to be logged in to see the file. Mindy says she is NOT experiencing this, but I am and so are our office staff. It does not matter which browser we are using.

This should not be the case. As long as we are logged in on the Admin page, we should be able to open files without having to be logged in on the user side.

**Comment by dpentony** [comment] 2016-07-14 20:07
We believe we have fully tested the auth changes for both ag and cte users. It appears to be working as intended. Other than the problem with opening the files from the Missing Files report on the admin page (see post above), we have not encountered any issues.

**Comment by bguerrettaz** [comment] 2016-07-17 18:40
Sounds good.  I've tried to recreate your issue, but haven't been able to.
Let me see if I understand completely:

- Log in to admin page
- Go to missing file report
- Try to open either a Lesson plan, eUnit or PPT and you get redirected to
login right then?

This is what I haven't been able to recreate.  If you could, please take a
quick video of the issue so that I can see you walk through it.

Outside of this issue, would you like me to move forward with the rest of
the changes, for deactivate dates?  I can probably have it installed by
mid-week.

Thanks,
Blake

**Comment by dpentony** [comment] 2016-07-17 21:06
I am unable to send a vidoe as I am traveling. Here are screenshots. What you did was correct in recreating the issue
1.
![image](https://cloud.githubusercontent.com/assets/5790325/16903037/cc421a34-4c37-11e6-98be-6ec53097b315.png)

2. 
![image](https://cloud.githubusercontent.com/assets/5790325/16903047/0db38c82-4c38-11e6-8193-aa64155ac80a.png)

3. 
![image](https://cloud.githubusercontent.com/assets/5790325/16903048/1f1c48ec-4c38-11e6-935a-59101cd3a1ee.png)

I would prefer to not move forward with the rest of the changes until this gets cleared up. I will be back in the office on Wednesday. Please let me know if you need more info.

**Comment by bguerrettaz** [comment] 2016-07-19 01:34
This has been resolved.  The rules engine was interpreting lesson plans on
the user side prior to the admin side, I've put them in the correct order.

Please test and confirm.

Thanks,
Blake

**Comment by dpentony** [comment] 2016-07-19 02:17
This is resolved for me. I just want  our people in the Danville office to make sure it works before I close this issue.

**Comment by dpentony** [comment] 2016-07-19 14:33
This looks good for all of us. Please proceed with the next sage of the changes.

**Comment by dpentony** [comment] 2016-07-25 12:59
@bguerrettaz  - what's the status of the rolling out the next stage of changes for the authentication?

**Comment by bguerrettaz** [comment] 2016-07-25 20:48
Ran into some issues over the weekend, working though those.  Hoping to
have it installed mid week.

Also, eUnit and Lesson Plans both have activation/deactivation date tables
to know when if they have access and until when.  PPT's do not have a table
like that and they aren't included in the lesson lookup table, like lessons
and eunits are.  How should these be handled from an access perspective?
Teacher deactivate date?

**Comment by dpentony** [comment] 2016-07-25 20:58
Access to PPTs should be controlled by deactivate dates of the lesson plans. The PPTs access is included when they order access to the lessons.

**Comment by bguerrettaz** [comment] 2016-07-25 21:01
Ok, makes sense. I just need to make sure that there is a table that
connects a certain PPT with a lesson plan.  If there is not, I'm not sure
how we'll connect the two...

**Comment by dpentony** [comment] 2016-07-25 21:05
Take a look at the Missing File report. That connects each PPT to its appropriate lesson.

**Comment by bguerrettaz** [comment] 2016-07-25 21:13
Good point, I'll check that out.  Thanks

**Comment by bguerrettaz** [comment] 2016-07-28 02:54
Ok, I have completed and installed the changes for eUnits and Lesson Plans
*only*.  I'm still working on PPT's.

Please note, if there are any issues that you find that interrupts business
as usual, please email me and I'll revert back the changes I have made.

Please test and confirm eUnits and Lesson Plans are working as desired.

Thanks,
Blake

**Comment by dpentony** [comment] 2016-07-28 12:51
@bguerrettaz - can you give us some insight on how best to test this?

**Comment by bguerrettaz** [comment] 2016-07-28 12:59
Some of the tests I ran was to go into a teacher/student account and test
Lesson Plans and eUnits, then go to the admin console, change the
deactivation date to something prior to today then retest, you should get
redirected to the home page of the account with a message saying you don't
have access to that content.

**Comment by dpentony** [comment] 2016-07-28 14:34
@bguerrettaz - we have started testing, but I think we need to have a conference call so that Mindy and I fully understand what we should be looking for. Please let us know when you would be available.

I did run into one issue in my early testing. Under my IL ag account, I have a course called 8.14.14. There are 11 Eunits assigned to that course. They are in the Hort library. I logged is as student Blake Guerrettaz (all classes) and could access the Eunits fine. I then changed the de-activate dates in the admin for the Hort Eunits to 1/1/2016. I then logged in as the same student and could not access the Eunits. However, I was re-directed to the TEACHER landing page. That is not correct. If I am a student trying to access Eunits and the teacher's access has expired, I should be re-directed to the Student landing page. We definitely don't want the kids to have access to the teacher pages.

**Comment by dpentony** [comment] 2016-07-28 19:31
We are getting an error message when trying to download PPTs. It is:

![image](https://cloud.githubusercontent.com/assets/5790325/17226601/db125bdc-54cf-11e6-8f89-be5089ee88d2.png)

**Comment by bguerrettaz** [comment] 2016-07-28 19:31
I should be able to do a call tomorrow at 8am, if that works for you guys?

I'll fix the issue you found with students tonight.

Blake

**Comment by dpentony** [comment] 2016-07-28 19:33
I think you might want to revert the changes if you believe that will address the PPT download problem. Or, if you can fix the issue tonight, you would not need to revert it.

**Comment by bguerrettaz** [comment] 2016-07-28 20:00
I have fixed the issue with PPT's not loading.  Please test and confirm.

I will fix the student access to teacher homepage issue this evening.

Blake

**Comment by dpentony** [comment] 2016-07-28 20:16
The PPT issue is fixed. Thanks.

Mindy and I will both be available after 8 AM tomorrow.

**Comment by bguerrettaz** [comment] 2016-07-28 20:17
Ok, do you want me to just call you and you can conference Mindy in?

**Comment by dpentony** [comment] 2016-07-28 20:26
I don't know how to conference her in. Any other ideas?

**Comment by bguerrettaz** [comment] 2016-07-28 20:27
@Brian - are you planning to call in? If not, can we use your conference
line?

**Comment by dpentony** [comment] 2016-07-28 21:01
Hey, I just own the phone system. I don't know how to use it!

MIndy figured out how to do a conference call. You can call her at 21.7446.0500, ext. 133 and she will conference me in.

**Comment by bguerrettaz** [comment] 2016-07-29 02:10
I have fixed the issue with students being redirected to their teachers
homepage.  Please test and confirm that is working as desired.

Blake

**Comment by dpentony** [comment] 2016-07-30 21:21
Yes

**Comment by dpentony** [comment] 2016-08-01 16:13
We've not identified any problems in our testing.

What is the next step?

**Comment by bguerrettaz** [comment] 2016-08-01 16:18
Good deal, next step is to bring in PowerPoints, working through that and
will install soon.

If you encounter any issues in the meantime, please let me know.

Again, once school resumes, if there is a big problem that we didn't
uncover in testing, I can revert back to the initial changes that requires
the user at least be logged in.

Thanks,
Blake

**Comment by bguerrettaz** [comment] 2016-08-02 02:25
i have installed the changes for PPT's.  Please test these changes as well.

If no issues are found, this will complete this work.

Blake

**Comment by dpentony** [comment] 2016-08-02 20:39
In testing this, neither Mindy or I can figure out how to get a PPT to open without it automatically downloading. Since it downloads automatically, we can't test the authentication on PPTs by pasting the link in our browser.

Any ideas? This only happens with PPTs.

**Comment by bguerrettaz** [comment] 2016-08-03 14:09
The way you can grab the link without clicking on it is by right clicking
the actual link for a PPT and selecting 'Copy Link Address'.  That way you
will have the link that is used and it will go through the authentication
process.

Blake

**Comment by bguerrettaz** [comment] 2016-08-03 20:30
Also, do you want me to turn off the alert regarding the July 1st changes
after a user logs in?

**Comment by dpentony** [comment] 2016-08-03 20:38
Please leave the alert regarding the July 1 changes. I think it is a good reminder to teachers as they come back to school. MY thought would be to leave it up until January 1.

**Comment by bguerrettaz** [comment] 2016-08-03 20:39
Ok, no problem.

**Comment by dpentony** [comment] 2016-08-04 13:41
All looks good as a result of our testing.

I am going to leave this issue open. The real testing will begin in the next few weeks as teachers return.

**Comment by bguerrettaz** [comment] 2016-08-04 13:41
Sounds good, thanks.

**Comment by dpentony** [comment] 2016-08-04 16:08
I've revised the title on this issue to better reflect what is encompasses.

**Closed** 2016-10-11 14:37 UTC
