### ISSUE TITLE
Students cannot submit quiz

### ISSUE THREAD

**Issue by mnichols13** [MyCaert/Issues-Enhancements#258] opened 2017-09-27 16:54 UTC
Since school has started this fall we have had issues where students cannot submit a quiz.  

Today: teacher Steven Mcgaha - South Carolina
students:  Adrian Martinez, Madelin Ramos
Quiz:  FFA Final Test Ag Science
Two students log into the site, the quiz gives the lines go through the page and gives the message that it has been viewed too many times.   When we checked the student views under the Edit quiz page, the students names do not appear as even viewing the quiz one time.  
I had to change the parameters to unlimited to allow the students to take the quiz. 
I checked to see if these students possibly took the quiz last year, but they did not.  

Can you look into this and see if you can find any issues?  Unfortunately this is not a situation where we can leave things as is for you to review, the teacher is waiting for a quick fix.

**Comment by mnichols13** [comment] 2017-10-02 18:05
Is there any update on this?

**Comment by bguerrettaz** [comment] 2017-10-03 01:55
Sorry I thought I sent a question:

I wasn’t able to simulate this, so you have steps I can take to recreate?  Without being able to recreate I can’t find the root cause.

Any additional information would be very helpful, thanks!

Blake

**Comment by mnichols13** [comment] 2017-10-03 12:35
I have  no way to recreate this.    Dan, any ideas?

**Comment by dpentony** [comment] 2017-10-03 12:51
I guess not. We will close it for now but may need to re-open. This is going to be a tough one to determine because if we don't employ the workaround, the students cannot take the test on the day teachers want them to take it.

**Comment by dpentony** [comment] 2017-10-04 16:10
This issue cropped up again for the third time this school year. We have a workaround but if we employ it, you can't see the problem. Please see Mindy's email of today regarding Jeni O'Connor in IL. Two students cannot take the test and we are waiting on you to see the issue before we employ the workaround.

**Comment by BrianPeterlin** [comment] 2017-10-04 16:14
I will increase capacity on the DB server and see if that corrects the issues

**Comment by dpentony** [comment] 2017-10-04 16:17
@BrianPeterlin - Did you see the issue? Can we employ the workaround?

**Comment by BrianPeterlin** [comment] 2017-10-04 16:21
yes, employ the workaround

**Comment by mnichols13** [comment] 2017-10-04 19:47
2nd complaint from the same teacher:
Something is not working right with the quiz feature.  I had a student take the 'special' quiz that you created and his answers were changed once it was graded.  He was using chrome, not explorer.  I printed out the quiz for him and he got an A+.  When he took the quiz and entered the same answers, he got a 55%.  I've had several students with issues such as this today (approx. 15 students).

**Comment by mnichols13** [comment] 2017-10-04 19:48
In order to allow the student to take the quiz online today, I created a 2nd course outline, copied the quiz and added the two students to this course roster.

**Comment by BrianPeterlin** [comment] 2017-10-04 20:12
Most likely that was the cause

The db is only showing 2 cores and it should have 4 cores.  I have a ticket opened with dell to determine what the issue is.

**Comment by bguerrettaz** [comment] 2017-10-04 20:42
Ok I’ll wait to hear back before investigating.

**Comment by dpentony** [comment] 2017-10-05 12:47
Any update from Dell?

**Comment by BrianPeterlin** [comment] 2017-10-05 12:57
I need to uninstall the drivers and reinstall.

**Comment by dpentony** [comment] 2017-10-05 13:03
When are you going to do that? Will it affect our users?

**Comment by mnichols13** [comment] 2017-10-05 13:20
Teacher reports continued problems this morning, she just called.  
Students unable to submit a quiz

**Comment by dpentony** [comment] 2017-10-05 13:47
Just so you are aware, this is the school where you do the bulk upload of students every year. I am not sure if that would be a contributing factor to the problems she is having.

**Comment by BrianPeterlin** [comment] 2017-10-05 15:13
@bguerrettaz, were any code changes recently made to the test page?

**Comment by dpentony** [comment] 2017-10-05 16:40
Just to be clear, when some students access the test for the first time, it shows that they have viewed it beyond the limits set in the test parameter. The teacher can change the number of views Under MY Quizzes>Edit Quiz>Views. When the teacher goes to change the number of views for a student on a particular test and then saves it, it is not updating. Thus, there is no way for the teacher to change the student views so they can take the test.

**Comment by bguerrettaz** [comment] 2017-10-05 17:16
Just to be certain, is this one teacher (the bulk upload teacher) or has it
happened with other teachers that hasn't had us bulk upload?

**Closed** 2017-10-12 13:20 UTC
